/*
 *  * rls.c: Remote directory listing client
 *   */


#include <stdio.h>
#include <rpc/rpc.h> /* always need this */
#include "./dir.h"	 /* will be generated by rpcgen */
#include <errno.h>
#include <stdlib.h>
#include <string.h>

//extern int errno;

main(argc, argv) int argc;
char *argv[];
{
	CLIENT *cl;
	char *server;
	char *command;
	char *dir;
	readdir_res *result;
	namelist nl;

	if (argc < 4)
	{
		printf("Not enough arguments. Please type %s host {0,1} input", argv[0]);
		exit(0);
	}
	else if (argc > 4)
	{
		printf("Too many arguments. Please type %s host  {0,1} input", argv[0]);
		exit(0);
	}
	else
	{
		server = argv[1];
		char expression = argv[2][0];

		switch (expression)

		{
		case ('0'):
			strcpy(command, "grep ");
			strcat(command, argv[3]);
			strcat(command, " -n ./server/*");
			break;

		case ('1'):
			strcpy(command, "find ");
			strcat(command, " server/ -name  \"");
			strcat(command, argv[3]);
			strcat(command, "\"");
			break;

		default:
			printf("Invalid argument  %c", expression);
			break;
		}
	}
	/*
										 *          * Create client "handle" used for calling DIRPROG on
										 *                   * the server designated on the command line.  Use
										 *                            * the tcp protocol when contacting the server.
										 *                                     */
	cl = clnt_create(server, DIRPROG, DIRVERS, "tcp");
	if (cl == NULL)
	{
		/*
														 *                  * Couldn't establish connection with server.
														 *                                   * Print error message and stop.
														 *                                                    */
		clnt_pcreateerror(server);
		exit(1);
	}

	/*
												 *          * Call the remote procedure readdir on the server
												 *                   */
	result = readdir_1(&command, cl);
	if (result == NULL)
	{
		/*
																 *                  * An RPC error occurred while calling the server.
																 *                                   * Print error message and stop.
																 *                                                    */
		clnt_perror(cl, server);
		exit(1);
	}

	/*
														 *          * Okay, we successfully called the remote procedure.
														 *                   */
	if (result->errnum != 0)
	{
		/*
																	 *                  * A remote system error occurred.
																	 *                                   * Print error message and stop.
																	 *                                                    */
		errno = result->errnum;
		perror(command);
		exit(1);
	}

	/*
															 *          * Successfully got a directory listing.
															 *                   * Print it out.
															 *                            */
	for (nl = result->readdir_res_u.list; nl != NULL;
		 nl = nl->next)
	{
		printf("%s\n", nl->name);
	}
	exit(0);
}

//Message to the evaluator:
/**
 * Editing of RPC calls is  done in rls.c , 
 * So i take all the inputs there, and perform string operations on them, 
 * only to send  the address of the final string to the dir_clnt.c, which forwards it to the server.
*/

